# TODO: create DEV profile with h2 configured but set production config as a default
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pem
  datasource:
#    name: dance
    username: dance
    password: PZNH7rF78wE
    url: jdbc:mariadb://127.0.0.1:3306/dance
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: on
    defer-datasource-initialization: on
  sql:
    init:
      mode: always
  mail:
    username: gilliamaa@gmail.com
    password: igmlpcaatkqfbsze
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: prod
  mvc:
    problemdetails:
      enabled: true
keys:
  pri: classpath:keys/private.pem
  pub: classpath:keys/public.pem
logging:
  level:
    root: debug
  file:
    path: ${HOME}