INSERT INTO user (role, email, step, password, phone_number, state, city)
VALUES ('DANCER', 'sadeghabedi@live.com', 1, '$2a$10$qCV5QuOyVSqrrIzq5TVfu.v3ZWU/XR/FVl/KX226qCerRKXLsfbPC',
        '+989390261196', 'California', 'Los Angeles'),
       ('DANCER', 'sadeghabedi36@gmail.com', 6, '$2a$10$qCV5QuOyVSqrrIzq5TVfu.v3ZWU/XR/FVl/KX226qCerRKXLsfbPC',
        '+989100501578', 'California', 'San Diego'),
       ('DANCER', 'zmmmken@gmail.com', 6, '$2y$10$VC6/PgzBiDmxfy5nE4csAOV.tXWA6lBeSH9vnyKqmtzWiz5J5048S',
        '+989158146043', 'Texas', 'Dallas');
INSERT INTO event (name, step, state, city, company_id)
VALUES ('An Event', 5, 'California', 'Los Angeles', 1),
       ('An Event Sample', 5, 'California', 'Los Angeles', 1),
       ('An Event Test', 5, 'California', 'Los Angeles', 2),
       ('An Event', 5, 'California', 'Los Angeles', 1),
       ('An Event Sample', 5, 'California', 'Los Angeles', 1),
       ('An Event Test', 5, 'California', 'Los Angeles', 2),
       ('Another Event', 5, 'California', 'San Diego', 1),
       ('Another Event Sample', 5, 'California', 'San Diego', 1),
       ('Another Event Test', 5, 'California', 'San Diego', 2),
       ('Another Event', 5, 'California', 'San Diego', 1),
       ('Another Event Sample', 5, 'California', 'San Diego', 1),
       ('Another Event Test', 5, 'California', 'San Diego', 2),
       ('Another Event', 5, 'California', 'San Diego', 3),
       ('An Event', 5, 'Texas', 'Dallas', 1),
       ('An Event Sample', 5, 'Texas', 'Dallas', 1),
       ('An Event Test', 5, 'Texas', 'Dallas', 2),
       ('An Event', 5, 'Texas', 'Dallas', 1),
       ('An Event Sample', 5, 'Texas', 'Dallas', 1),
       ('An Event Test', 5, 'Texas', 'Dallas', 2),
       ('Another Event', 5, 'Texas', 'Dallas', 1),
       ('Another Event Sample', 5, 'Texas', 'Dallas', 1),
       ('Another Event Test', 5, 'Texas', 'Dallas', 2),
       ('Another Event', 5, 'Texas', 'Dallas', 1),
       ('Another Event Sample', 5, 'Texas', 'Dallas', 1),
       ('Another Event Test', 5, 'Texas', 'Dallas', 2),
       ('Another Event', 5, 'Texas', 'Dallas', 3);